Vapor/Vapor/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from clientApp.views import HomePageView, register
from account.views import UserDetail
from game.views import GameList, GameDetail, UserGameList, gameOrder, gameRate

urlpatterns = [

    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),

    # User views
    url(r'^accounts/profile/$', UserDetail.as_view(), name='accounts_profile'),
    url(r'^register/$', register, name='register'),
    # Game views
    url(r'^games/$', GameList.as_view(), name='game_list'),
    url(r'^mygames/$', login_required(UserGameList.as_view()), name='user_game_list'),
    url(r'^games/(?P<pk>[0-9]+)/$', GameDetail.as_view(), name='game_detail'),
    url(r'^gameOrder/$', gameOrder, name='game_order'),
    url(r'^gameRate/$', gameRate, name='game_rate'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

Vapor/dbModels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class Genre(models.Model):
	name = models.CharField(primary_key = True, max_length = 50)

	def __unicode__(self):
		return self.name

class Platform(models.Model):
	name = models.CharField(primary_key = True, max_length = 50)

	def __unicode__(self):
		return self.name

class Tag(models.Model):
	name = models.CharField(primary_key = True, max_length = 50)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']

class Vendor(models.Model):
	name = models.CharField(primary_key = True, max_length = 50)

	def __unicode__(self):
		return self.name

class CPU(models.Model):
	id = models.AutoField(primary_key = True)
	vendor = models.ForeignKey(Vendor)
	name = models.CharField(max_length = 50)

	def __unicode__(self):
		return self.name

	class Meta:
		unique_together = ('vendor', 'name')

class GPU(models.Model):
	id = models.AutoField(primary_key = True)
	vendor = models.ForeignKey(Vendor)
	name = models.CharField(max_length = 50)

	def __unicode__(self):
		return self.name

	class Meta:
		unique_together = ('vendor', 'name')

class GameStudio(models.Model):
	name = models.CharField(primary_key = True, max_length = 100)
	synopsis = models.CharField(max_length = 1000)
	url = models.URLField(max_length = 200)

	def __unicode__(self):
		return self.name

class GameTitle(models.Model):
	id = models.AutoField(primary_key = True)
	genre_name = models.ForeignKey(Genre)
	name = models.CharField(max_length = 100)
	synopsis = models.CharField(max_length = 1000)
	picture = models.ImageField(null = True, upload_to = 'games')

	studio = models.ManyToManyField(GameStudio, through = 'GameWasReleased', through_fields = ('game_title', 'studio')) # game was released
	tag = models.ManyToManyField(Tag, through = 'GameHasTag', through_fields = ('game_title', 'tag')) # game has tag

	def __unicode__(self):
		return self.name

class Game(models.Model):
	id = models.AutoField(primary_key = True)
	platform = models.ForeignKey(Platform)
	title = models.ForeignKey(GameTitle)
	release_date = models.DateTimeField()
	price = models.DecimalField(max_digits = 10, decimal_places = 2)

	ratings = models.ManyToManyField(User, through = 'Rating', through_fields = ('game', 'user'), related_name='users_that_rated')
	owners = models.ManyToManyField(User, through = 'Orders', through_fields = ('game', 'user'), related_name='users_that_owned')

	def __unicode__(self):
		return self.title.name

	def clean(self):
		if self.price <= 0:
			raise ValidationError('Price has to be bigger than zero!')

class GameWasReleased(models.Model):
	game_title = models.ForeignKey(GameTitle)
	studio = models.ForeignKey(GameStudio)

	class Meta:
		unique_together = ('game_title', 'studio')

class GameHasTag(models.Model):
	game_title = models.ForeignKey(GameTitle)
	tag = models.ForeignKey(Tag)

	class Meta:
		unique_together = ('game_title', 'tag')

class Rating(models.Model):
	user = models.ForeignKey(User)
	game = models.ForeignKey(Game)
	rating = models.IntegerField()

	class Meta:
		unique_together = ('user', 'game')

	def clean(self):
		if self.rating < 0 or self.rating > 10:
			raise ValidationError('Rating needs to be in a range of 1 to 10.')

class Orders(models.Model):
	id = models.AutoField(primary_key = True)
	user = models.ForeignKey(User)
	game = models.ForeignKey(Game)
	date = models.DateTimeField()
	price = models.DecimalField(max_digits = 10, decimal_places = 2)

	class Meta:
		unique_together = ('user', 'game')

class Comments(models.Model):
	id = models.AutoField(primary_key = True)
	user = models.ForeignKey(User)
	game = models.ForeignKey(Game)
	date = models.DateTimeField()
	content = models.CharField(max_length = 2000)

class CommentsArchive(models.Model):
	id = models.AutoField(primary_key = True)
	comment_id = models.IntegerField(null = False)
	modification_date = models.DateTimeField()
	content = models.CharField(max_length = 2000)

class GameMinCPU(models.Model): 
	game = models.ForeignKey(Game)
	cpu = models.ForeignKey(CPU)

	class Meta:
		unique_together = ('game', 'cpu')

class GameRecommendedCPU(models.Model):
	game = models.ForeignKey(Game)
	cpu = models.ForeignKey(CPU)

	class Meta:
		unique_together = ('game', 'cpu')

class GameMinGPU(models.Model):
	game = models.ForeignKey(Game)
	gpu = models.ForeignKey(GPU)

	class Meta:
		unique_together = ('game', 'gpu')

class GameRecommendedGPU(models.Model): 
	game = models.ForeignKey(Game)
	gpu = models.ForeignKey(GPU)

	class Meta:
		unique_together = ('game', 'gpu')

class RequiredRam(models.Model):
	game = models.ForeignKey(Game, unique = True)
	minimum = models.IntegerField(verbose_name = 'Minimum RAM [GB]') 
	recommended = models.IntegerField(verbose_name = 'Recommended RAM [GB]') 

	def clean(self):
		if self.minimum > self.recommended:
			raise ValidationError('Minimum requirements can not to be higher than recommended requirements!')

	def __unicode__(self):
		return ""

class Sale(models.Model):
	id = models.AutoField(primary_key = True)
	game = models.ForeignKey(Game)
	start_date = models.DateTimeField()
	end_date = models.DateTimeField()
	factor = models.FloatField()

	def __unicode__(self):
		return str(self.game.title)


# Add your models here.

Vapor/game/models.py
from django.db import models

# Create your models here.

Vapor/game/forms.py
from django import forms
from django.contrib.auth.models import User
from dbModels.models import Orders, Platform, Genre, Game, Tag
from django.forms import inlineformset_factory


class GameFilterForm(forms.Form):

    PLATFORMS = [(i.name, i.name) for i in Platform.objects.all()]
    PLATFORMS.insert(0, ("", "All"))

    GENRES = [(i.name, i.name) for i in Genre.objects.all()]
    GENRES.insert(0, ("", "All"))

    TAGS = [(i.name, i.name) for i in Tag.objects.all()]
    TAGS.insert(0, ("", "All"))

    title = forms.CharField(required=False)
    genre = forms.ChoiceField(required=False, widget=forms.Select, choices=GENRES)
    platform = forms.ChoiceField(required=False, widget=forms.Select, choices=PLATFORMS)
    tag = forms.ChoiceField(required=False, widget=forms.Select, choices=TAGS)

Vapor/game/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from dbModels.models import GameTitle, Orders, Game, Rating
from .forms import GameFilterForm
from datetime import datetime
from django.db.models import Avg


class GameList(ListView):
    template_name = 'game/game_list.html'

    def get_queryset(self):
        titles = GameTitle.objects.all()

        form = GameFilterForm(self.request.GET)
        if form.is_valid():
            title = form.cleaned_data['title']
            genre = form.cleaned_data['genre']
            platform = form.cleaned_data['platform']
            tag = form.cleaned_data['tag']

            if title:
                titles = titles.filter(name__icontains=title)

            if genre:
                titles = titles.filter(genre_name__name=genre)

            if platform:
                titles = titles.filter(game__platform__name=platform)

            if tag:
                titles = titles.filter(tag__name=tag)

        titles = titles.annotate(rating=Avg('game__rating__rating'))

        return titles

    def get_context_data(self, **kwargs):
        context = super(GameList, self).get_context_data(**kwargs)
        context['form'] = GameFilterForm(self.request.GET)

        return context


class GameDetail(DetailView):
    template_name = 'game/game_detail.html'
    model = GameTitle;

#@login_required(login_url='/accounts/login/')
class UserGameList(GameList):
    template_name = 'game/game_list.html'

    # def get_queryset(self):
    #     #titles = super(UserGameList, self).get_queryset().filter(game__owners = self.request.user).distinct()
    #     titles = [i.title for i in Game.objects.filter(owners=self.request.user)]
    #     print titles
    #     return titles

    def get_context_data(self, **kwargs):
        context = super(UserGameList, self).get_context_data(**kwargs)
        titles = super(UserGameList, self).get_queryset().filter(game__owners=self.request.user).distinct()
        context['object_list'] = titles
        context['games'] = Game.objects.filter(owners=self.request.user)

        return context


def gameOrder(request):
   if request.method == 'POST':
        platform = request.POST['platform']
        game = Game.objects.get(id=platform)
        user = request.user
        try:
            order = Orders.objects.get(game = game, user = user)
        except Orders.DoesNotExist:
            order = None
        if order:
            messages.error(request, "You have already bought that game!")
        else:
            order = Orders(game = game, user = user, date = datetime.now(), price = game.price)
            order.save()
            messages.success(request, "Thank you for buying the game! We hope you will enjoy playing!")

        return HttpResponseRedirect('/games/' + str(game.title.id) + '/')
   else:
        return HttpResponseRedirect('/')

def gameRate(request):
   if request.method == 'POST':
        rate = request.POST['rate']
        game = request.POST['game']
        game = Game.objects.get(id=game)
        user = request.user
        try:
            rating = Rating.objects.get(game = game, user = user)
            rating.rating = rate
        except Rating.DoesNotExist:
            rating = Rating(game = game, user = user, rating = rate)
        rating.save();

        return HttpResponseRedirect('/games/' + str(game.title.id) + '/')
   else:
        return HttpResponseRedirect('/')

Vapor/game/templates/game/game_detail.html
{% extends "base.html" %}
{% block content %}
<h1 class="page-header" xmlns="http://www.w3.org/1999/html">{{ object.title.name }}</h1>
<div id="game-cover-photo" class="col-md-3">
    <img src="/static/{{ object.picture.url }}" style="width: 100%;"/>
</div>
<div id="game-info" class="col-md-4">
    <table class="table">
        <thead class="">
        <tr>
        <th>Name:</th>
        <th>{{ object.name }}
        </th>
      </tr></thead>
    <tbody>
      <tr>
        <td>About game:</td>
        <td>{{ object.synopsis }}</td>
      </tr>
      <tr>
        <td>Genre</td>
        <td>{{ object.genre_name }}</td>
      </tr>
      <tr>
        <td>Tags</td>
        <td>
        {% for tag in object.tag.all %}
            <label class="label label-info">
                <i class="fa fa-tag"></i>
                {{tag}}
            </label>
        {% endfor %}
        </td>
      </tr>
    </tbody>
  </table>
    </div>
<div id="game-platforms" class="col-md-4">
<table class="table">
    <thead>
        <tr>
            <td>Platform available</td>
            {% if user.is_authenticated %}
                <td>My rating</td>
            {% endif %}
            <td>Price</td>
        </tr>
    </thead>
    <tbody>
    {% for game in object.game_set.all %}
        <tr>
            <td><h3><label class="label label-primary">
                {% if "windows" in game.platform.name|lower %}<i class="fa fa-lg fa-windows "></i> {% endif %}
                {% if "android" in game.platform.name|lower %}<i class="fa fa-lg fa-android"></i> {% endif %}
                {% if "linux" in game.platform.name|lower %}<i class="fa fa-lg fa-linux"></i> {% endif %}
                {% if "xbox" in game.platform.name|lower %}<i class="fa fa-lg fa-gamepad"></i> {% endif %}
                {% if "playstation" in game.platform.name|lower %}<i class="fa fa-lg fa-gamepad"></i> {% endif %}
                {{ game.platform.name }}
            </label></h3>
            </td>
            {% if user.is_authenticated %}
            <td><h3>


                     <form action="/gameRate/" method="post">
                     {% csrf_token %}
                    <input type="hidden" name="game" value="{{game.id}}">
                    <input type="hidden" class="form-control rate-input" name="rate" onchange="this.form.submit()">

                     <div class="btn-group">
                         <button type="button" class="btn
                          {% for rate in game.rating_set.all %}
                            {% if rate.user.id == user.id %}
                             {% if rate.rating > 8 %}
                             btn-success
                            {% elif rate.rating > 6 %}
                            btn-primary
                            {% elif rate.rating > 4 %}
                            btn-info
                            {% elif rate.rating > 2 %}
                            btn-warning
                            {% elif rate.rating >= 0 %}
                            btn-danger
                            {% endif %}
                            {% endif %}
                        {% endfor %}
                          dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                             Rating:
                         {% for rate in game.rating_set.all %}
                            {% if rate.user.id == user.id %}
                             {{ rate.rating }}
                            {% endif %}
                        {% endfor %}
                             <span class="caret"></span>
                        </button>
                         <ul class="dropdown-menu" role="menu">
                             {% with '0 1 2 3 4 5 6 7 8 9 10' as list %}
                             {% for i in list.split %}
                                <li><a class = "change-rate" href="#">{{ i }}</a></li>
                             {% endfor %}
                             {% endwith %}
                         </ul>
                     </div>
                     </form>
            </h3></td>
            {% endif%}
            <td><h3><label class="label label-success">{{ game.price }}$</label></h3></td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% if user.is_authenticated %}
<div id="game-buy" class="col-md-9 pull-right">

<form action="/gameOrder/" method="POST">
    {% csrf_token %}

    <label for="platform">Choose platform:</label>
    <select class="form-control" name="platform" id="platform">
        {% for game in object.game_set.all %}
            <option value="{{ game.id }}">{{ game.platform.name }}</option>
        {% endfor %}
    </select>
    <br/>
    <input type="submit" class="btn btn-success btn-lg pull-right" value="Give us money! Buy the game!" style="width: 100%;"/>
</form>
</div>
{%endif%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
    $(".change-rate").click( function(event){
    var x = $(event.target).text();
    $(event.target).parents("td").first().find(".rate-input").first().val(x);
    $(event.target).parents("td").first().find("form").submit();
    });
});
</script>
{% endblock %}

Vapor/game/templates/game/game_list.html
{% extends "base.html" %}

{% block content %}
<h1 class="page-header">Games</h1>

<form id="filterForm" action="{{ request.path }}" method="get">
    {{ form }}
    <input type="submit" value="Filter" class="btn btn-default btn-sm" />
    <button type="button" class="btn btn-default btn-sm" onclick="clearFilters()">Clear</button>
</form>

<div class="list-group">
    {% for title in object_list %}
        <a href="/games/{{ title.id }}" class="list-group-item">
            <h4 class="list-group-item-heading">
                {{ title.name }}
            </h4>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <span>Genre: {{ title.genre_name.name }}</span>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <span class="list-group-item-text">Rating:
                        {% if title.rating %}
                            {{ title.rating|stringformat:".1f" }}
                        {% else %}
                            No ratings yet
                        {% endif %}
                    </span>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <span class="list-group-item-text">
                        {% for game in title.game_set.all %}
                            {% if game in games or not games %}
                                <label class="label label-default">
                                {% if "windows" in game.platform.name|lower %}<i class="fa fa-lg fa-windows"></i> {% endif %}
                                {% if "android" in game.platform.name|lower %}<i class="fa fa-lg fa-android"></i> {% endif %}
                                {% if "linux" in game.platform.name|lower %}<i class="fa fa-lg fa-linux"></i> {% endif %}
                                {% if "xbox" in game.platform.name|lower %}<i class="fa fa-lg fa-gamepad"></i> {% endif %}
                                {% if "playstation" in game.platform.name|lower %}<i class="fa fa-lg fa-gamepad"></i> {% endif %}
                                {{ game.platform.name }}</label>
                                </label>
                            {% endif %}
                        {% endfor %}
                    </span>
                </div>
            </div>
          </a>
    {% endfor %}
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function clearFilters() {
        $("#id_title").val("");
        $("#id_genre").val("");
        $("#id_platform").val("");
        $("#id_tag").val("");
        $("#filterForm").submit();
    }
</script>
{% endblock %}